import type { Static } from "typebox";
import {
  ArtifactDescriptor,
  BinaryHttpBodyFixture,
  SoulDescriptor,
  SseHeartbeatFixture,
} from "./artifacts.js";
import {
  CommandReceipt,
  CommandResult,
  ConversationCommand,
  CreateConversationResponse,
  DialogResponse,
  ForkResult,
  ModelCycleResult,
  SessionChangeResult,
  ThinkingCycleResult,
  commandTypeValues,
} from "./commands.js";
import {
  ConversationRef,
  DirectoryConversationRef,
  EmptyRequest,
  GatewayConversationRef,
  GatewayWorkspaceRef,
  HealthResult,
  JsonObject,
  JsonValue,
  ProblemDetails,
  ProtocolVersion,
  StatusResult,
  ThinkingLevel,
  ValidationIssue,
} from "./common.js";
import {
  CommandsResult,
  Conversation,
  ConversationPage,
  ConversationState,
  ConversationSummary,
  CreateConversationRequest,
  EntriesResult,
  ForkMessagesResult,
  ImageInput,
  LastAssistantResult,
  MessagesResult,
  ThinkingLevelsResult,
  TreeResult,
} from "./conversations.js";
import {
  ActiveResponse,
  ActiveToolExecution,
  AssistantMessageEvent,
  ConversationEvent,
  ConversationSnapshot,
  ExtensionUiEvent,
  GatewayEvent,
  GatewaySnapshot,
  PendingDialog,
  SafeExtensionSource,
  ToolResultData,
} from "./events.js";
import {
  AssistantMessage,
  AssistantMessageDiagnostic,
  BashExecutionMessage,
  BashResultDto,
  BranchSummaryEntry,
  BranchSummaryMessage,
  CommandSourceRef,
  CommandSummary,
  CompactionEntry,
  CompactionResultDto,
  CompactionSummaryMessage,
  ContextUsage,
  CustomEntry,
  CustomMessage,
  CustomMessageEntry,
  DiagnosticErrorInfo,
  ImageContent,
  LabelEntry,
  ModelChangeEntry,
  PiContentBlock,
  PiEntry,
  PiMessage,
  PiTreeNode,
  SessionInfoEntry,
  SessionMessageEntry,
  SessionStats,
  TextContent,
  ThinkingContent,
  ThinkingLevelChangeEntry,
  ToolCall,
  ToolResultMessage,
  Usage,
  UserMessage,
} from "./pi.js";
import {
  ModelSummary,
  ModelsResult,
  ProviderAuthNotification,
  ProviderAuthPrompt,
  ProviderAuthType,
  ProviderLoginRequest,
  ProviderLoginResult,
  ProviderSummary,
  ProvidersResult,
} from "./providers.js";
import {
  CreateWorkspaceRequest,
  UpdateWorkspaceRequest,
  Workspace,
  WorkspacePage,
} from "./workspaces.js";

export const schemaRegistry = {
  ActiveResponse,
  ActiveToolExecution,
  ArtifactDescriptor,
  AssistantMessage,
  AssistantMessageDiagnostic,
  AssistantMessageEvent,
  BashExecutionMessage,
  BashResultDto,
  BinaryHttpBodyFixture,
  BranchSummaryEntry,
  BranchSummaryMessage,
  CommandReceipt,
  CommandResult,
  CommandSourceRef,
  CommandsResult,
  CommandSummary,
  CompactionEntry,
  CompactionResultDto,
  CompactionSummaryMessage,
  ContextUsage,
  Conversation,
  ConversationCommand,
  ConversationEvent,
  ConversationPage,
  ConversationRef,
  ConversationSnapshot,
  ConversationState,
  ConversationSummary,
  CreateConversationRequest,
  CreateConversationResponse,
  CreateWorkspaceRequest,
  CustomEntry,
  CustomMessage,
  CustomMessageEntry,
  DiagnosticErrorInfo,
  DialogResponse,
  DirectoryConversationRef,
  EmptyRequest,
  EntriesResult,
  ExtensionUiEvent,
  ForkMessagesResult,
  ForkResult,
  GatewayConversationRef,
  GatewayEvent,
  GatewaySnapshot,
  GatewayWorkspaceRef,
  HealthResult,
  ImageContent,
  ImageInput,
  JsonObject,
  JsonValue,
  LabelEntry,
  LastAssistantResult,
  MessagesResult,
  ModelChangeEntry,
  ModelCycleResult,
  ModelsResult,
  ModelSummary,
  PendingDialog,
  PiContentBlock,
  PiEntry,
  PiMessage,
  PiTreeNode,
  ProblemDetails,
  ProtocolVersion,
  ProviderAuthNotification,
  ProviderAuthPrompt,
  ProviderAuthType,
  ProviderLoginRequest,
  ProviderLoginResult,
  ProviderSummary,
  ProvidersResult,
  SafeExtensionSource,
  SessionChangeResult,
  SessionInfoEntry,
  SessionMessageEntry,
  SessionStats,
  SoulDescriptor,
  SseHeartbeatFixture,
  StatusResult,
  TextContent,
  ThinkingContent,
  ThinkingCycleResult,
  ThinkingLevel,
  ThinkingLevelChangeEntry,
  ThinkingLevelsResult,
  ToolCall,
  ToolResultData,
  ToolResultMessage,
  TreeResult,
  UpdateWorkspaceRequest,
  Usage,
  UserMessage,
  ValidationIssue,
  Workspace,
  WorkspacePage,
} as const;

export type SchemaName = keyof typeof schemaRegistry;
export type SchemaType<Name extends SchemaName> = Static<(typeof schemaRegistry)[Name]>;
export const commandTypes = Object.freeze([...commandTypeValues]);
